### PR TITLE
Update vscode-languageclient to 7.0.0

### PR DESCRIPTION
**Pull request by berberman**
Tested on my machine, this could fix https://github.com/haskell/haskell-language-server/issues/2068.

### CODE REVIEW

**Comment by jneira** [comment]
nice, good catch, only a bit worried in case users has not upgrade their editors (for whatever reason)
is this the lastest one?

**Comment by berberman** [comment]
The version `1.52.0` is from the lsp extension guide (https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), and it's the latest version. Maybe an older vscode can work, which at least should include the support of semantic tokens. I don't know what the exact bound is, but imho people should always keep their editors up-to-date.

By specifying `engines.vscode: "^1.52.0"`, the extension won't be loaded if a user's vscode version is older than that.

**Comment by pepeiborra** [comment]
@berberman did you confirm that this fixes haskell/haskell-language-server#2068 ?

**Comment by berberman** [comment]
> @berberman did you confirm that this fixes [haskell/haskell-language-server#2068](https://github.com/haskell/haskell-language-server/issues/2068) ?

Yes, at least on my laptop

**Pull request merged**
