### PR TITLE
Add applyrefact:applyAll command as hie.commands.applyall

### PR DESCRIPTION
**Pull request by expipiplus1**
I've never used typescript before today!

### CODE REVIEW

**Comment by alanz** [comment]
@expipiplus1 can you rebase this against master, I think the tests may now be passing. Then we can see about merging and another release.

**Comment by expipiplus1** [comment]
done, thanks!

**Comment by alanz** [comment]
@expipiplus1 Please resolve the conflict, sorry.

**Comment by expipiplus1** [comment]
@alanz, done, thanks

**Comment by alanz** [comment]
@expipiplus1 Sorry to do this to you, but it struck me that it might be more universal to add this as a command exposed by `hie`, which is then available to all clients.

**Comment by expipiplus1** [comment]
@alanz, sorry I think I'm missing something; isn't that already the case, and this change is just making the `applyrefact:applyall` command available to vscode?

**Comment by alanz** [comment]
@expipiplus1 I think we can do this in a way that does not need specific code in the client to be able to use the feature.

This is a desirable way of doing things, because then it will work across more different clients.

**Comment by expipiplus1** [comment]
Ah I see, I'm happy either way

**Comment by jneira** [comment]
Hi, as i am translating the hlint plugin from hie to hls i would like to revisit this one. I think expose `applyAll` as a command could be handy, even if we register it in the lang server in some way.
It would let users execute it using the command palette, emacs style, or the file [editor context menu](https://code.visualstudio.com/api/references/contribution-points#contributes.menus). Maybe i am used to other ides like eclipse but i expect to see file wide actions in those locations.

**Comment by expipiplus1** [comment]
@jneira I've rebased this to be on top of master. I'm not able to test with vscode, however a very similar patch works well with coc.nvim.

@bubba You had some thoughts about the registering commands in this extension, so your thoughts are appreciated.

**Comment by bubba** [comment]
@expipiplus1 These commands are for the hlint code actions right? As long as the language server (HLS) is handling them then the vscode extension shouldn't need to register for them from what I understand

**Comment by expipiplus1** [comment]
@bubba That's what I would have assumed too, however @chemzqm (of coc.nvim) suggested writing an extension before when I had a similar query: https://github.com/neoclide/coc.nvim/issues/1277#issuecomment-

**Comment by bubba** [comment]
Hmm the specification doesn't really say much about `capabilities.executeCommandProvider.commands` or ExecuteCommandOptions. Presumably this is just to advertise "permanent" commands that can be executed anytime. But I don't think it's a prerequisite for actually executing them is it? Do the hints work without the changes in this PR?

**Comment by expipiplus1** [comment]
> Do the hints work without the changes in this PR?

The command to applyAll doesn't appear without this PR.

The hints aren't applying either way at the moment, but that's a separate issue ;)

**Comment by alanz** [comment]
Something to bear in mind.

VsCode manages a single registry of commands available to execute. If you open more than one haskell project in vscode, it runs more than one LSP server. The commands they register go into a single table.

To avoid ambiguity, when the haskell language server registers a command, it prefixes it with the process number.  So statically registering a command in the extension won't work.

And I once more note that I think this is the wrong thing to do.

**Comment by expipiplus1** [comment]
Alanz, agree entirely that is this is possible without logic on the extension then that's clearly the way to go. I just have no idea how to do that.

This does however seem to work for me (in coc.nvim and vscode), at least for my simple 1 client 1 server setup.

Perhaps it would be possible to merge (or merge if someone could help with the process number thing) and at a later date remove it when the server advertises the command properly.

**Comment by jneira** [comment]
The hlint plugin is already offering an `apply all` quick fix, so maybe this is not needed @expipiplus1?

**Comment by expipiplus1** [comment]
Yeah, happy to close this. Thanks for the thoughtful feedback all.

**Pull request closed without merging**
