### PR TITLE
Improve serverExecutablePath missing error message

### PR DESCRIPTION
**Pull request by bubba**

### CODE REVIEW

**Comment by georgefst** [comment]
If I'm reading the code correctly here, it seems that the PATH variable is being completely ignored once we reach this point, and we're passing an absolute path to `executableExists` (which means we may as well just check for existence of that path).

In which case, better would be something like:

`serverExecutablePath is set to ${exePath}, which does not exist`

**Comment by bubba** [comment]
`executableExists` is just a call to `which` so it will check the PATH, but will also work for absolute filepaths given too. But good point, should probably cover both bases with `serverExecutablePath is set to ${exePath}, which does not exist or is not on the PATH`

**Comment by bubba** [comment]
@georgefst Updated the help text for the setting

**Comment by georgefst** [comment]
Perfect.

**Pull request merged**
